// Generated by gencpp from file feetech_controls/jointcontrols.msg
// DO NOT EDIT!


#ifndef FEETECH_CONTROLS_MESSAGE_JOINTCONTROLS_H
#define FEETECH_CONTROLS_MESSAGE_JOINTCONTROLS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace feetech_controls
{
template <class ContainerAllocator>
struct jointcontrols_
{
  typedef jointcontrols_<ContainerAllocator> Type;

  jointcontrols_()
    : id(0)
    , jointvalues(0.0)  {
    }
  jointcontrols_(const ContainerAllocator& _alloc)
    : id(0)
    , jointvalues(0.0)  {
  (void)_alloc;
    }



   typedef int16_t _id_type;
  _id_type id;

   typedef double _jointvalues_type;
  _jointvalues_type jointvalues;





  typedef boost::shared_ptr< ::feetech_controls::jointcontrols_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::feetech_controls::jointcontrols_<ContainerAllocator> const> ConstPtr;

}; // struct jointcontrols_

typedef ::feetech_controls::jointcontrols_<std::allocator<void> > jointcontrols;

typedef boost::shared_ptr< ::feetech_controls::jointcontrols > jointcontrolsPtr;
typedef boost::shared_ptr< ::feetech_controls::jointcontrols const> jointcontrolsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::feetech_controls::jointcontrols_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::feetech_controls::jointcontrols_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::feetech_controls::jointcontrols_<ContainerAllocator1> & lhs, const ::feetech_controls::jointcontrols_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.jointvalues == rhs.jointvalues;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::feetech_controls::jointcontrols_<ContainerAllocator1> & lhs, const ::feetech_controls::jointcontrols_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace feetech_controls

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::feetech_controls::jointcontrols_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::feetech_controls::jointcontrols_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::feetech_controls::jointcontrols_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::feetech_controls::jointcontrols_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::feetech_controls::jointcontrols_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::feetech_controls::jointcontrols_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::feetech_controls::jointcontrols_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7988f738ee37fb27a094c2d2252a41df";
  }

  static const char* value(const ::feetech_controls::jointcontrols_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7988f738ee37fb27ULL;
  static const uint64_t static_value2 = 0xa094c2d2252a41dfULL;
};

template<class ContainerAllocator>
struct DataType< ::feetech_controls::jointcontrols_<ContainerAllocator> >
{
  static const char* value()
  {
    return "feetech_controls/jointcontrols";
  }

  static const char* value(const ::feetech_controls::jointcontrols_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::feetech_controls::jointcontrols_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 id\n"
"float64 jointvalues\n"
;
  }

  static const char* value(const ::feetech_controls::jointcontrols_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::feetech_controls::jointcontrols_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.jointvalues);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct jointcontrols_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::feetech_controls::jointcontrols_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::feetech_controls::jointcontrols_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
    s << indent << "jointvalues: ";
    Printer<double>::stream(s, indent + "  ", v.jointvalues);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FEETECH_CONTROLS_MESSAGE_JOINTCONTROLS_H
