// Generated by gencpp from file feetech_controls/jointfeedback.msg
// DO NOT EDIT!


#ifndef FEETECH_CONTROLS_MESSAGE_JOINTFEEDBACK_H
#define FEETECH_CONTROLS_MESSAGE_JOINTFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace feetech_controls
{
template <class ContainerAllocator>
struct jointfeedback_
{
  typedef jointfeedback_<ContainerAllocator> Type;

  jointfeedback_()
    : jointvalues()  {
    }
  jointfeedback_(const ContainerAllocator& _alloc)
    : jointvalues(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _jointvalues_type;
  _jointvalues_type jointvalues;





  typedef boost::shared_ptr< ::feetech_controls::jointfeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::feetech_controls::jointfeedback_<ContainerAllocator> const> ConstPtr;

}; // struct jointfeedback_

typedef ::feetech_controls::jointfeedback_<std::allocator<void> > jointfeedback;

typedef boost::shared_ptr< ::feetech_controls::jointfeedback > jointfeedbackPtr;
typedef boost::shared_ptr< ::feetech_controls::jointfeedback const> jointfeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::feetech_controls::jointfeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::feetech_controls::jointfeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::feetech_controls::jointfeedback_<ContainerAllocator1> & lhs, const ::feetech_controls::jointfeedback_<ContainerAllocator2> & rhs)
{
  return lhs.jointvalues == rhs.jointvalues;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::feetech_controls::jointfeedback_<ContainerAllocator1> & lhs, const ::feetech_controls::jointfeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace feetech_controls

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::feetech_controls::jointfeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::feetech_controls::jointfeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::feetech_controls::jointfeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::feetech_controls::jointfeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::feetech_controls::jointfeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::feetech_controls::jointfeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::feetech_controls::jointfeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a9d4993eb244bba482f1be1b903382b4";
  }

  static const char* value(const ::feetech_controls::jointfeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa9d4993eb244bba4ULL;
  static const uint64_t static_value2 = 0x82f1be1b903382b4ULL;
};

template<class ContainerAllocator>
struct DataType< ::feetech_controls::jointfeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "feetech_controls/jointfeedback";
  }

  static const char* value(const ::feetech_controls::jointfeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::feetech_controls::jointfeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] jointvalues\n"
;
  }

  static const char* value(const ::feetech_controls::jointfeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::feetech_controls::jointfeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.jointvalues);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct jointfeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::feetech_controls::jointfeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::feetech_controls::jointfeedback_<ContainerAllocator>& v)
  {
    s << indent << "jointvalues[]" << std::endl;
    for (size_t i = 0; i < v.jointvalues.size(); ++i)
    {
      s << indent << "  jointvalues[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.jointvalues[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FEETECH_CONTROLS_MESSAGE_JOINTFEEDBACK_H
