// Generated by gencpp from file feetech_controls/readjointvaluesRequest.msg
// DO NOT EDIT!


#ifndef FEETECH_CONTROLS_MESSAGE_READJOINTVALUESREQUEST_H
#define FEETECH_CONTROLS_MESSAGE_READJOINTVALUESREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace feetech_controls
{
template <class ContainerAllocator>
struct readjointvaluesRequest_
{
  typedef readjointvaluesRequest_<ContainerAllocator> Type;

  readjointvaluesRequest_()
    : idstart(0)
    , idend(0)  {
    }
  readjointvaluesRequest_(const ContainerAllocator& _alloc)
    : idstart(0)
    , idend(0)  {
  (void)_alloc;
    }



   typedef int64_t _idstart_type;
  _idstart_type idstart;

   typedef int64_t _idend_type;
  _idend_type idend;





  typedef boost::shared_ptr< ::feetech_controls::readjointvaluesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::feetech_controls::readjointvaluesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct readjointvaluesRequest_

typedef ::feetech_controls::readjointvaluesRequest_<std::allocator<void> > readjointvaluesRequest;

typedef boost::shared_ptr< ::feetech_controls::readjointvaluesRequest > readjointvaluesRequestPtr;
typedef boost::shared_ptr< ::feetech_controls::readjointvaluesRequest const> readjointvaluesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::feetech_controls::readjointvaluesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::feetech_controls::readjointvaluesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::feetech_controls::readjointvaluesRequest_<ContainerAllocator1> & lhs, const ::feetech_controls::readjointvaluesRequest_<ContainerAllocator2> & rhs)
{
  return lhs.idstart == rhs.idstart &&
    lhs.idend == rhs.idend;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::feetech_controls::readjointvaluesRequest_<ContainerAllocator1> & lhs, const ::feetech_controls::readjointvaluesRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace feetech_controls

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::feetech_controls::readjointvaluesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::feetech_controls::readjointvaluesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::feetech_controls::readjointvaluesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::feetech_controls::readjointvaluesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::feetech_controls::readjointvaluesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::feetech_controls::readjointvaluesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::feetech_controls::readjointvaluesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3686e6221b7224d0bb35c49c32d8e79d";
  }

  static const char* value(const ::feetech_controls::readjointvaluesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3686e6221b7224d0ULL;
  static const uint64_t static_value2 = 0xbb35c49c32d8e79dULL;
};

template<class ContainerAllocator>
struct DataType< ::feetech_controls::readjointvaluesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "feetech_controls/readjointvaluesRequest";
  }

  static const char* value(const ::feetech_controls::readjointvaluesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::feetech_controls::readjointvaluesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 idstart\n"
"int64 idend\n"
;
  }

  static const char* value(const ::feetech_controls::readjointvaluesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::feetech_controls::readjointvaluesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.idstart);
      stream.next(m.idend);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct readjointvaluesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::feetech_controls::readjointvaluesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::feetech_controls::readjointvaluesRequest_<ContainerAllocator>& v)
  {
    s << indent << "idstart: ";
    Printer<int64_t>::stream(s, indent + "  ", v.idstart);
    s << indent << "idend: ";
    Printer<int64_t>::stream(s, indent + "  ", v.idend);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FEETECH_CONTROLS_MESSAGE_READJOINTVALUESREQUEST_H
