// Generated by gencpp from file feetech_controls/readjointvalues.msg
// DO NOT EDIT!


#ifndef FEETECH_CONTROLS_MESSAGE_READJOINTVALUES_H
#define FEETECH_CONTROLS_MESSAGE_READJOINTVALUES_H

#include <ros/service_traits.h>


#include <feetech_controls/readjointvaluesRequest.h>
#include <feetech_controls/readjointvaluesResponse.h>


namespace feetech_controls
{

struct readjointvalues
{

typedef readjointvaluesRequest Request;
typedef readjointvaluesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct readjointvalues
} // namespace feetech_controls


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::feetech_controls::readjointvalues > {
  static const char* value()
  {
    return "21a5fa9eeca5ec0f0f497e63ffbb5aa1";
  }

  static const char* value(const ::feetech_controls::readjointvalues&) { return value(); }
};

template<>
struct DataType< ::feetech_controls::readjointvalues > {
  static const char* value()
  {
    return "feetech_controls/readjointvalues";
  }

  static const char* value(const ::feetech_controls::readjointvalues&) { return value(); }
};


// service_traits::MD5Sum< ::feetech_controls::readjointvaluesRequest> should match
// service_traits::MD5Sum< ::feetech_controls::readjointvalues >
template<>
struct MD5Sum< ::feetech_controls::readjointvaluesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::feetech_controls::readjointvalues >::value();
  }
  static const char* value(const ::feetech_controls::readjointvaluesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::feetech_controls::readjointvaluesRequest> should match
// service_traits::DataType< ::feetech_controls::readjointvalues >
template<>
struct DataType< ::feetech_controls::readjointvaluesRequest>
{
  static const char* value()
  {
    return DataType< ::feetech_controls::readjointvalues >::value();
  }
  static const char* value(const ::feetech_controls::readjointvaluesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::feetech_controls::readjointvaluesResponse> should match
// service_traits::MD5Sum< ::feetech_controls::readjointvalues >
template<>
struct MD5Sum< ::feetech_controls::readjointvaluesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::feetech_controls::readjointvalues >::value();
  }
  static const char* value(const ::feetech_controls::readjointvaluesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::feetech_controls::readjointvaluesResponse> should match
// service_traits::DataType< ::feetech_controls::readjointvalues >
template<>
struct DataType< ::feetech_controls::readjointvaluesResponse>
{
  static const char* value()
  {
    return DataType< ::feetech_controls::readjointvalues >::value();
  }
  static const char* value(const ::feetech_controls::readjointvaluesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FEETECH_CONTROLS_MESSAGE_READJOINTVALUES_H
