// Generated by gencpp from file feetech_controls/readjointvaluesResponse.msg
// DO NOT EDIT!


#ifndef FEETECH_CONTROLS_MESSAGE_READJOINTVALUESRESPONSE_H
#define FEETECH_CONTROLS_MESSAGE_READJOINTVALUESRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace feetech_controls
{
template <class ContainerAllocator>
struct readjointvaluesResponse_
{
  typedef readjointvaluesResponse_<ContainerAllocator> Type;

  readjointvaluesResponse_()
    : jointreadvalues()  {
    }
  readjointvaluesResponse_(const ContainerAllocator& _alloc)
    : jointreadvalues(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _jointreadvalues_type;
  _jointreadvalues_type jointreadvalues;





  typedef boost::shared_ptr< ::feetech_controls::readjointvaluesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::feetech_controls::readjointvaluesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct readjointvaluesResponse_

typedef ::feetech_controls::readjointvaluesResponse_<std::allocator<void> > readjointvaluesResponse;

typedef boost::shared_ptr< ::feetech_controls::readjointvaluesResponse > readjointvaluesResponsePtr;
typedef boost::shared_ptr< ::feetech_controls::readjointvaluesResponse const> readjointvaluesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::feetech_controls::readjointvaluesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::feetech_controls::readjointvaluesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::feetech_controls::readjointvaluesResponse_<ContainerAllocator1> & lhs, const ::feetech_controls::readjointvaluesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.jointreadvalues == rhs.jointreadvalues;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::feetech_controls::readjointvaluesResponse_<ContainerAllocator1> & lhs, const ::feetech_controls::readjointvaluesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace feetech_controls

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::feetech_controls::readjointvaluesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::feetech_controls::readjointvaluesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::feetech_controls::readjointvaluesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::feetech_controls::readjointvaluesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::feetech_controls::readjointvaluesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::feetech_controls::readjointvaluesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::feetech_controls::readjointvaluesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f7e1ffb0293b88553551dedfd053500a";
  }

  static const char* value(const ::feetech_controls::readjointvaluesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf7e1ffb0293b8855ULL;
  static const uint64_t static_value2 = 0x3551dedfd053500aULL;
};

template<class ContainerAllocator>
struct DataType< ::feetech_controls::readjointvaluesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "feetech_controls/readjointvaluesResponse";
  }

  static const char* value(const ::feetech_controls::readjointvaluesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::feetech_controls::readjointvaluesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] jointreadvalues\n"
"\n"
;
  }

  static const char* value(const ::feetech_controls::readjointvaluesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::feetech_controls::readjointvaluesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.jointreadvalues);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct readjointvaluesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::feetech_controls::readjointvaluesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::feetech_controls::readjointvaluesResponse_<ContainerAllocator>& v)
  {
    s << indent << "jointreadvalues[]" << std::endl;
    for (size_t i = 0; i < v.jointreadvalues.size(); ++i)
    {
      s << indent << "  jointreadvalues[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.jointreadvalues[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FEETECH_CONTROLS_MESSAGE_READJOINTVALUESRESPONSE_H
