// Generated by gencpp from file feetech_controls/torqcontrolResponse.msg
// DO NOT EDIT!


#ifndef FEETECH_CONTROLS_MESSAGE_TORQCONTROLRESPONSE_H
#define FEETECH_CONTROLS_MESSAGE_TORQCONTROLRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace feetech_controls
{
template <class ContainerAllocator>
struct torqcontrolResponse_
{
  typedef torqcontrolResponse_<ContainerAllocator> Type;

  torqcontrolResponse_()
    : idret()  {
    }
  torqcontrolResponse_(const ContainerAllocator& _alloc)
    : idret(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _idret_type;
  _idret_type idret;





  typedef boost::shared_ptr< ::feetech_controls::torqcontrolResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::feetech_controls::torqcontrolResponse_<ContainerAllocator> const> ConstPtr;

}; // struct torqcontrolResponse_

typedef ::feetech_controls::torqcontrolResponse_<std::allocator<void> > torqcontrolResponse;

typedef boost::shared_ptr< ::feetech_controls::torqcontrolResponse > torqcontrolResponsePtr;
typedef boost::shared_ptr< ::feetech_controls::torqcontrolResponse const> torqcontrolResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::feetech_controls::torqcontrolResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::feetech_controls::torqcontrolResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::feetech_controls::torqcontrolResponse_<ContainerAllocator1> & lhs, const ::feetech_controls::torqcontrolResponse_<ContainerAllocator2> & rhs)
{
  return lhs.idret == rhs.idret;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::feetech_controls::torqcontrolResponse_<ContainerAllocator1> & lhs, const ::feetech_controls::torqcontrolResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace feetech_controls

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::feetech_controls::torqcontrolResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::feetech_controls::torqcontrolResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::feetech_controls::torqcontrolResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::feetech_controls::torqcontrolResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::feetech_controls::torqcontrolResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::feetech_controls::torqcontrolResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::feetech_controls::torqcontrolResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e389d92e542b074a29a72824fadc4d53";
  }

  static const char* value(const ::feetech_controls::torqcontrolResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe389d92e542b074aULL;
  static const uint64_t static_value2 = 0x29a72824fadc4d53ULL;
};

template<class ContainerAllocator>
struct DataType< ::feetech_controls::torqcontrolResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "feetech_controls/torqcontrolResponse";
  }

  static const char* value(const ::feetech_controls::torqcontrolResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::feetech_controls::torqcontrolResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool[] idret\n"
"\n"
;
  }

  static const char* value(const ::feetech_controls::torqcontrolResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::feetech_controls::torqcontrolResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.idret);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct torqcontrolResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::feetech_controls::torqcontrolResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::feetech_controls::torqcontrolResponse_<ContainerAllocator>& v)
  {
    s << indent << "idret[]" << std::endl;
    for (size_t i = 0; i < v.idret.size(); ++i)
    {
      s << indent << "  idret[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.idret[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FEETECH_CONTROLS_MESSAGE_TORQCONTROLRESPONSE_H
