// Generated by gencpp from file feetech_controls/torqcontrol.msg
// DO NOT EDIT!


#ifndef FEETECH_CONTROLS_MESSAGE_TORQCONTROL_H
#define FEETECH_CONTROLS_MESSAGE_TORQCONTROL_H

#include <ros/service_traits.h>


#include <feetech_controls/torqcontrolRequest.h>
#include <feetech_controls/torqcontrolResponse.h>


namespace feetech_controls
{

struct torqcontrol
{

typedef torqcontrolRequest Request;
typedef torqcontrolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct torqcontrol
} // namespace feetech_controls


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::feetech_controls::torqcontrol > {
  static const char* value()
  {
    return "c7fd7facee233a061827f86f586e5d13";
  }

  static const char* value(const ::feetech_controls::torqcontrol&) { return value(); }
};

template<>
struct DataType< ::feetech_controls::torqcontrol > {
  static const char* value()
  {
    return "feetech_controls/torqcontrol";
  }

  static const char* value(const ::feetech_controls::torqcontrol&) { return value(); }
};


// service_traits::MD5Sum< ::feetech_controls::torqcontrolRequest> should match
// service_traits::MD5Sum< ::feetech_controls::torqcontrol >
template<>
struct MD5Sum< ::feetech_controls::torqcontrolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::feetech_controls::torqcontrol >::value();
  }
  static const char* value(const ::feetech_controls::torqcontrolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::feetech_controls::torqcontrolRequest> should match
// service_traits::DataType< ::feetech_controls::torqcontrol >
template<>
struct DataType< ::feetech_controls::torqcontrolRequest>
{
  static const char* value()
  {
    return DataType< ::feetech_controls::torqcontrol >::value();
  }
  static const char* value(const ::feetech_controls::torqcontrolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::feetech_controls::torqcontrolResponse> should match
// service_traits::MD5Sum< ::feetech_controls::torqcontrol >
template<>
struct MD5Sum< ::feetech_controls::torqcontrolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::feetech_controls::torqcontrol >::value();
  }
  static const char* value(const ::feetech_controls::torqcontrolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::feetech_controls::torqcontrolResponse> should match
// service_traits::DataType< ::feetech_controls::torqcontrol >
template<>
struct DataType< ::feetech_controls::torqcontrolResponse>
{
  static const char* value()
  {
    return DataType< ::feetech_controls::torqcontrol >::value();
  }
  static const char* value(const ::feetech_controls::torqcontrolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FEETECH_CONTROLS_MESSAGE_TORQCONTROL_H
