// Generated by gencpp from file feetech_controls/torqcontrolRequest.msg
// DO NOT EDIT!


#ifndef FEETECH_CONTROLS_MESSAGE_TORQCONTROLREQUEST_H
#define FEETECH_CONTROLS_MESSAGE_TORQCONTROLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace feetech_controls
{
template <class ContainerAllocator>
struct torqcontrolRequest_
{
  typedef torqcontrolRequest_<ContainerAllocator> Type;

  torqcontrolRequest_()
    : idrec()  {
    }
  torqcontrolRequest_(const ContainerAllocator& _alloc)
    : idrec(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int64_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int64_t>> _idrec_type;
  _idrec_type idrec;





  typedef boost::shared_ptr< ::feetech_controls::torqcontrolRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::feetech_controls::torqcontrolRequest_<ContainerAllocator> const> ConstPtr;

}; // struct torqcontrolRequest_

typedef ::feetech_controls::torqcontrolRequest_<std::allocator<void> > torqcontrolRequest;

typedef boost::shared_ptr< ::feetech_controls::torqcontrolRequest > torqcontrolRequestPtr;
typedef boost::shared_ptr< ::feetech_controls::torqcontrolRequest const> torqcontrolRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::feetech_controls::torqcontrolRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::feetech_controls::torqcontrolRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::feetech_controls::torqcontrolRequest_<ContainerAllocator1> & lhs, const ::feetech_controls::torqcontrolRequest_<ContainerAllocator2> & rhs)
{
  return lhs.idrec == rhs.idrec;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::feetech_controls::torqcontrolRequest_<ContainerAllocator1> & lhs, const ::feetech_controls::torqcontrolRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace feetech_controls

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::feetech_controls::torqcontrolRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::feetech_controls::torqcontrolRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::feetech_controls::torqcontrolRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::feetech_controls::torqcontrolRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::feetech_controls::torqcontrolRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::feetech_controls::torqcontrolRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::feetech_controls::torqcontrolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6a8e3aac2c8c93d18c703f7cf71f88e";
  }

  static const char* value(const ::feetech_controls::torqcontrolRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6a8e3aac2c8c93dULL;
  static const uint64_t static_value2 = 0x18c703f7cf71f88eULL;
};

template<class ContainerAllocator>
struct DataType< ::feetech_controls::torqcontrolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "feetech_controls/torqcontrolRequest";
  }

  static const char* value(const ::feetech_controls::torqcontrolRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::feetech_controls::torqcontrolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64[] idrec\n"
;
  }

  static const char* value(const ::feetech_controls::torqcontrolRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::feetech_controls::torqcontrolRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.idrec);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct torqcontrolRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::feetech_controls::torqcontrolRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::feetech_controls::torqcontrolRequest_<ContainerAllocator>& v)
  {
    s << indent << "idrec[]" << std::endl;
    for (size_t i = 0; i < v.idrec.size(); ++i)
    {
      s << indent << "  idrec[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.idrec[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FEETECH_CONTROLS_MESSAGE_TORQCONTROLREQUEST_H
