// Generated by gencpp from file feetech_controls/headcontrols.msg
// DO NOT EDIT!


#ifndef FEETECH_CONTROLS_MESSAGE_HEADCONTROLS_H
#define FEETECH_CONTROLS_MESSAGE_HEADCONTROLS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace feetech_controls
{
template <class ContainerAllocator>
struct headcontrols_
{
  typedef headcontrols_<ContainerAllocator> Type;

  headcontrols_()
    : arucoid(0)
    , type(0)
    , headjointvalues1(0.0)
    , headjointvalues2(0.0)  {
    }
  headcontrols_(const ContainerAllocator& _alloc)
    : arucoid(0)
    , type(0)
    , headjointvalues1(0.0)
    , headjointvalues2(0.0)  {
  (void)_alloc;
    }



   typedef int16_t _arucoid_type;
  _arucoid_type arucoid;

   typedef int16_t _type_type;
  _type_type type;

   typedef float _headjointvalues1_type;
  _headjointvalues1_type headjointvalues1;

   typedef float _headjointvalues2_type;
  _headjointvalues2_type headjointvalues2;





  typedef boost::shared_ptr< ::feetech_controls::headcontrols_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::feetech_controls::headcontrols_<ContainerAllocator> const> ConstPtr;

}; // struct headcontrols_

typedef ::feetech_controls::headcontrols_<std::allocator<void> > headcontrols;

typedef boost::shared_ptr< ::feetech_controls::headcontrols > headcontrolsPtr;
typedef boost::shared_ptr< ::feetech_controls::headcontrols const> headcontrolsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::feetech_controls::headcontrols_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::feetech_controls::headcontrols_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::feetech_controls::headcontrols_<ContainerAllocator1> & lhs, const ::feetech_controls::headcontrols_<ContainerAllocator2> & rhs)
{
  return lhs.arucoid == rhs.arucoid &&
    lhs.type == rhs.type &&
    lhs.headjointvalues1 == rhs.headjointvalues1 &&
    lhs.headjointvalues2 == rhs.headjointvalues2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::feetech_controls::headcontrols_<ContainerAllocator1> & lhs, const ::feetech_controls::headcontrols_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace feetech_controls

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::feetech_controls::headcontrols_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::feetech_controls::headcontrols_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::feetech_controls::headcontrols_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::feetech_controls::headcontrols_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::feetech_controls::headcontrols_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::feetech_controls::headcontrols_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::feetech_controls::headcontrols_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1bdf8924bc3daacda9a890695dd945ec";
  }

  static const char* value(const ::feetech_controls::headcontrols_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1bdf8924bc3daacdULL;
  static const uint64_t static_value2 = 0xa9a890695dd945ecULL;
};

template<class ContainerAllocator>
struct DataType< ::feetech_controls::headcontrols_<ContainerAllocator> >
{
  static const char* value()
  {
    return "feetech_controls/headcontrols";
  }

  static const char* value(const ::feetech_controls::headcontrols_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::feetech_controls::headcontrols_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 arucoid\n"
"int16 type\n"
"float32 headjointvalues1\n"
"float32 headjointvalues2\n"
;
  }

  static const char* value(const ::feetech_controls::headcontrols_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::feetech_controls::headcontrols_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.arucoid);
      stream.next(m.type);
      stream.next(m.headjointvalues1);
      stream.next(m.headjointvalues2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct headcontrols_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::feetech_controls::headcontrols_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::feetech_controls::headcontrols_<ContainerAllocator>& v)
  {
    s << indent << "arucoid: ";
    Printer<int16_t>::stream(s, indent + "  ", v.arucoid);
    s << indent << "type: ";
    Printer<int16_t>::stream(s, indent + "  ", v.type);
    s << indent << "headjointvalues1: ";
    Printer<float>::stream(s, indent + "  ", v.headjointvalues1);
    s << indent << "headjointvalues2: ";
    Printer<float>::stream(s, indent + "  ", v.headjointvalues2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FEETECH_CONTROLS_MESSAGE_HEADCONTROLS_H
