// Generated by gencpp from file sort_track/TrackedObjects.msg
// DO NOT EDIT!


#ifndef SORT_TRACK_MESSAGE_TRACKEDOBJECTS_H
#define SORT_TRACK_MESSAGE_TRACKEDOBJECTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Header.h>
#include <sort_track/TrackedObject.h>

namespace sort_track
{
template <class ContainerAllocator>
struct TrackedObjects_
{
  typedef TrackedObjects_<ContainerAllocator> Type;

  TrackedObjects_()
    : header()
    , image_header()
    , objects()  {
    }
  TrackedObjects_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , image_header(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Header_<ContainerAllocator>  _image_header_type;
  _image_header_type image_header;

   typedef std::vector< ::sort_track::TrackedObject_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::sort_track::TrackedObject_<ContainerAllocator> >> _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::sort_track::TrackedObjects_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sort_track::TrackedObjects_<ContainerAllocator> const> ConstPtr;

}; // struct TrackedObjects_

typedef ::sort_track::TrackedObjects_<std::allocator<void> > TrackedObjects;

typedef boost::shared_ptr< ::sort_track::TrackedObjects > TrackedObjectsPtr;
typedef boost::shared_ptr< ::sort_track::TrackedObjects const> TrackedObjectsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sort_track::TrackedObjects_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sort_track::TrackedObjects_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sort_track::TrackedObjects_<ContainerAllocator1> & lhs, const ::sort_track::TrackedObjects_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.image_header == rhs.image_header &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sort_track::TrackedObjects_<ContainerAllocator1> & lhs, const ::sort_track::TrackedObjects_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sort_track

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sort_track::TrackedObjects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sort_track::TrackedObjects_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sort_track::TrackedObjects_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sort_track::TrackedObjects_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sort_track::TrackedObjects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sort_track::TrackedObjects_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sort_track::TrackedObjects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a44e334ae2403a52c52d73709b5b3461";
  }

  static const char* value(const ::sort_track::TrackedObjects_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa44e334ae2403a52ULL;
  static const uint64_t static_value2 = 0xc52d73709b5b3461ULL;
};

template<class ContainerAllocator>
struct DataType< ::sort_track::TrackedObjects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sort_track/TrackedObjects";
  }

  static const char* value(const ::sort_track::TrackedObjects_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sort_track::TrackedObjects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"std_msgs/Header image_header\n"
"TrackedObject[] objects\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sort_track/TrackedObject\n"
"int32 xmin\n"
"int32 ymin\n"
"int32 xmax\n"
"int32 ymax\n"
"int32 id\n"
"int32 center_x\n"
"int32 center_y\n"
"\n"
;
  }

  static const char* value(const ::sort_track::TrackedObjects_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sort_track::TrackedObjects_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.image_header);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackedObjects_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sort_track::TrackedObjects_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sort_track::TrackedObjects_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "image_header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.image_header);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sort_track::TrackedObject_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SORT_TRACK_MESSAGE_TRACKEDOBJECTS_H
