// Generated by gencpp from file sort_track/TrackedObject.msg
// DO NOT EDIT!


#ifndef SORT_TRACK_MESSAGE_TRACKEDOBJECT_H
#define SORT_TRACK_MESSAGE_TRACKEDOBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sort_track
{
template <class ContainerAllocator>
struct TrackedObject_
{
  typedef TrackedObject_<ContainerAllocator> Type;

  TrackedObject_()
    : xmin(0)
    , ymin(0)
    , xmax(0)
    , ymax(0)
    , id(0)
    , center_x(0)
    , center_y(0)  {
    }
  TrackedObject_(const ContainerAllocator& _alloc)
    : xmin(0)
    , ymin(0)
    , xmax(0)
    , ymax(0)
    , id(0)
    , center_x(0)
    , center_y(0)  {
  (void)_alloc;
    }



   typedef int32_t _xmin_type;
  _xmin_type xmin;

   typedef int32_t _ymin_type;
  _ymin_type ymin;

   typedef int32_t _xmax_type;
  _xmax_type xmax;

   typedef int32_t _ymax_type;
  _ymax_type ymax;

   typedef int32_t _id_type;
  _id_type id;

   typedef int32_t _center_x_type;
  _center_x_type center_x;

   typedef int32_t _center_y_type;
  _center_y_type center_y;





  typedef boost::shared_ptr< ::sort_track::TrackedObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sort_track::TrackedObject_<ContainerAllocator> const> ConstPtr;

}; // struct TrackedObject_

typedef ::sort_track::TrackedObject_<std::allocator<void> > TrackedObject;

typedef boost::shared_ptr< ::sort_track::TrackedObject > TrackedObjectPtr;
typedef boost::shared_ptr< ::sort_track::TrackedObject const> TrackedObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sort_track::TrackedObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sort_track::TrackedObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sort_track::TrackedObject_<ContainerAllocator1> & lhs, const ::sort_track::TrackedObject_<ContainerAllocator2> & rhs)
{
  return lhs.xmin == rhs.xmin &&
    lhs.ymin == rhs.ymin &&
    lhs.xmax == rhs.xmax &&
    lhs.ymax == rhs.ymax &&
    lhs.id == rhs.id &&
    lhs.center_x == rhs.center_x &&
    lhs.center_y == rhs.center_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sort_track::TrackedObject_<ContainerAllocator1> & lhs, const ::sort_track::TrackedObject_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sort_track

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sort_track::TrackedObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sort_track::TrackedObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sort_track::TrackedObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sort_track::TrackedObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sort_track::TrackedObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sort_track::TrackedObject_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sort_track::TrackedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9768f179b9235be5f03960ec9dc550a9";
  }

  static const char* value(const ::sort_track::TrackedObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9768f179b9235be5ULL;
  static const uint64_t static_value2 = 0xf03960ec9dc550a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::sort_track::TrackedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sort_track/TrackedObject";
  }

  static const char* value(const ::sort_track::TrackedObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sort_track::TrackedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 xmin\n"
"int32 ymin\n"
"int32 xmax\n"
"int32 ymax\n"
"int32 id\n"
"int32 center_x\n"
"int32 center_y\n"
"\n"
;
  }

  static const char* value(const ::sort_track::TrackedObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sort_track::TrackedObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xmin);
      stream.next(m.ymin);
      stream.next(m.xmax);
      stream.next(m.ymax);
      stream.next(m.id);
      stream.next(m.center_x);
      stream.next(m.center_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackedObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sort_track::TrackedObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sort_track::TrackedObject_<ContainerAllocator>& v)
  {
    s << indent << "xmin: ";
    Printer<int32_t>::stream(s, indent + "  ", v.xmin);
    s << indent << "ymin: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ymin);
    s << indent << "xmax: ";
    Printer<int32_t>::stream(s, indent + "  ", v.xmax);
    s << indent << "ymax: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ymax);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "center_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.center_x);
    s << indent << "center_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.center_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SORT_TRACK_MESSAGE_TRACKEDOBJECT_H
