// Generated by gencpp from file ros_hand_gesture_recognition/HandGesture.msg
// DO NOT EDIT!


#ifndef ROS_HAND_GESTURE_RECOGNITION_MESSAGE_HANDGESTURE_H
#define ROS_HAND_GESTURE_RECOGNITION_MESSAGE_HANDGESTURE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace ros_hand_gesture_recognition
{
template <class ContainerAllocator>
struct HandGesture_
{
  typedef HandGesture_<ContainerAllocator> Type;

  HandGesture_()
    : header()
    , gesture_name()
    , pose()  {
    }
  HandGesture_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gesture_name(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _gesture_name_type;
  _gesture_name_type gesture_name;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::ros_hand_gesture_recognition::HandGesture_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_hand_gesture_recognition::HandGesture_<ContainerAllocator> const> ConstPtr;

}; // struct HandGesture_

typedef ::ros_hand_gesture_recognition::HandGesture_<std::allocator<void> > HandGesture;

typedef boost::shared_ptr< ::ros_hand_gesture_recognition::HandGesture > HandGesturePtr;
typedef boost::shared_ptr< ::ros_hand_gesture_recognition::HandGesture const> HandGestureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_hand_gesture_recognition::HandGesture_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_hand_gesture_recognition::HandGesture_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_hand_gesture_recognition::HandGesture_<ContainerAllocator1> & lhs, const ::ros_hand_gesture_recognition::HandGesture_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.gesture_name == rhs.gesture_name &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_hand_gesture_recognition::HandGesture_<ContainerAllocator1> & lhs, const ::ros_hand_gesture_recognition::HandGesture_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_hand_gesture_recognition

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_hand_gesture_recognition::HandGesture_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_hand_gesture_recognition::HandGesture_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_hand_gesture_recognition::HandGesture_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_hand_gesture_recognition::HandGesture_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_hand_gesture_recognition::HandGesture_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_hand_gesture_recognition::HandGesture_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_hand_gesture_recognition::HandGesture_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2a74601111d83781469252b75af91b3";
  }

  static const char* value(const ::ros_hand_gesture_recognition::HandGesture_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2a74601111d8378ULL;
  static const uint64_t static_value2 = 0x1469252b75af91b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_hand_gesture_recognition::HandGesture_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_hand_gesture_recognition/HandGesture";
  }

  static const char* value(const ::ros_hand_gesture_recognition::HandGesture_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_hand_gesture_recognition::HandGesture_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"string gesture_name\n"
"geometry_msgs/Pose pose\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::ros_hand_gesture_recognition::HandGesture_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_hand_gesture_recognition::HandGesture_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gesture_name);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HandGesture_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_hand_gesture_recognition::HandGesture_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_hand_gesture_recognition::HandGesture_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gesture_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.gesture_name);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_HAND_GESTURE_RECOGNITION_MESSAGE_HANDGESTURE_H
