(cl:defpackage feetech_controls-srv
  (:use )
  (:export
   "READJOINTVALUES"
   "<READJOINTVALUES-REQUEST>"
   "READJOINTVALUES-REQUEST"
   "<READJOINTVALUES-RESPONSE>"
   "READJOINTVALUES-RESPONSE"
   "TORQCONTROL"
   "<TORQCONTROL-REQUEST>"
   "TORQCONTROL-REQUEST"
   "<TORQCONTROL-RESPONSE>"
   "TORQCONTROL-RESPONSE"
  ))

