// Generated by gencpp from file rfid/rfid_msg.msg
// DO NOT EDIT!


#ifndef RFID_MESSAGE_RFID_MSG_H
#define RFID_MESSAGE_RFID_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rfid
{
template <class ContainerAllocator>
struct rfid_msg_
{
  typedef rfid_msg_<ContainerAllocator> Type;

  rfid_msg_()
    : header()
    , epc()
    , time(0)
    , idx(0)
    , mode(0)
    , ant(0)
    , phase(0.0)
    , rssi(0.0)  {
    }
  rfid_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , epc(_alloc)
    , time(0)
    , idx(0)
    , mode(0)
    , ant(0)
    , phase(0.0)
    , rssi(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _epc_type;
  _epc_type epc;

   typedef uint64_t _time_type;
  _time_type time;

   typedef uint32_t _idx_type;
  _idx_type idx;

   typedef uint32_t _mode_type;
  _mode_type mode;

   typedef uint32_t _ant_type;
  _ant_type ant;

   typedef double _phase_type;
  _phase_type phase;

   typedef double _rssi_type;
  _rssi_type rssi;





  typedef boost::shared_ptr< ::rfid::rfid_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rfid::rfid_msg_<ContainerAllocator> const> ConstPtr;

}; // struct rfid_msg_

typedef ::rfid::rfid_msg_<std::allocator<void> > rfid_msg;

typedef boost::shared_ptr< ::rfid::rfid_msg > rfid_msgPtr;
typedef boost::shared_ptr< ::rfid::rfid_msg const> rfid_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rfid::rfid_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rfid::rfid_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rfid::rfid_msg_<ContainerAllocator1> & lhs, const ::rfid::rfid_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.epc == rhs.epc &&
    lhs.time == rhs.time &&
    lhs.idx == rhs.idx &&
    lhs.mode == rhs.mode &&
    lhs.ant == rhs.ant &&
    lhs.phase == rhs.phase &&
    lhs.rssi == rhs.rssi;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rfid::rfid_msg_<ContainerAllocator1> & lhs, const ::rfid::rfid_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rfid

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rfid::rfid_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rfid::rfid_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rfid::rfid_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rfid::rfid_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rfid::rfid_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rfid::rfid_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rfid::rfid_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c4700ac787e3c2aae4f451754e549da";
  }

  static const char* value(const ::rfid::rfid_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c4700ac787e3c2aULL;
  static const uint64_t static_value2 = 0xae4f451754e549daULL;
};

template<class ContainerAllocator>
struct DataType< ::rfid::rfid_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rfid/rfid_msg";
  }

  static const char* value(const ::rfid::rfid_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rfid::rfid_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"string epc\n"
"uint64 time\n"
"uint32 idx\n"
"uint32 mode\n"
"uint32 ant\n"
"float64 phase\n"
"float64 rssi\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rfid::rfid_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rfid::rfid_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.epc);
      stream.next(m.time);
      stream.next(m.idx);
      stream.next(m.mode);
      stream.next(m.ant);
      stream.next(m.phase);
      stream.next(m.rssi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rfid_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rfid::rfid_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rfid::rfid_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "epc: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.epc);
    s << indent << "time: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.time);
    s << indent << "idx: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.idx);
    s << indent << "mode: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.mode);
    s << indent << "ant: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.ant);
    s << indent << "phase: ";
    Printer<double>::stream(s, indent + "  ", v.phase);
    s << indent << "rssi: ";
    Printer<double>::stream(s, indent + "  ", v.rssi);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RFID_MESSAGE_RFID_MSG_H
