// Generated by gencpp from file zed_interfaces/reset_roi.msg
// DO NOT EDIT!


#ifndef ZED_INTERFACES_MESSAGE_RESET_ROI_H
#define ZED_INTERFACES_MESSAGE_RESET_ROI_H

#include <ros/service_traits.h>


#include <zed_interfaces/reset_roiRequest.h>
#include <zed_interfaces/reset_roiResponse.h>


namespace zed_interfaces
{

struct reset_roi
{

typedef reset_roiRequest Request;
typedef reset_roiResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct reset_roi
} // namespace zed_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::zed_interfaces::reset_roi > {
  static const char* value()
  {
    return "e1e87fc9e9e6c154eca93b9fa292cc05";
  }

  static const char* value(const ::zed_interfaces::reset_roi&) { return value(); }
};

template<>
struct DataType< ::zed_interfaces::reset_roi > {
  static const char* value()
  {
    return "zed_interfaces/reset_roi";
  }

  static const char* value(const ::zed_interfaces::reset_roi&) { return value(); }
};


// service_traits::MD5Sum< ::zed_interfaces::reset_roiRequest> should match
// service_traits::MD5Sum< ::zed_interfaces::reset_roi >
template<>
struct MD5Sum< ::zed_interfaces::reset_roiRequest>
{
  static const char* value()
  {
    return MD5Sum< ::zed_interfaces::reset_roi >::value();
  }
  static const char* value(const ::zed_interfaces::reset_roiRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::zed_interfaces::reset_roiRequest> should match
// service_traits::DataType< ::zed_interfaces::reset_roi >
template<>
struct DataType< ::zed_interfaces::reset_roiRequest>
{
  static const char* value()
  {
    return DataType< ::zed_interfaces::reset_roi >::value();
  }
  static const char* value(const ::zed_interfaces::reset_roiRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::zed_interfaces::reset_roiResponse> should match
// service_traits::MD5Sum< ::zed_interfaces::reset_roi >
template<>
struct MD5Sum< ::zed_interfaces::reset_roiResponse>
{
  static const char* value()
  {
    return MD5Sum< ::zed_interfaces::reset_roi >::value();
  }
  static const char* value(const ::zed_interfaces::reset_roiResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::zed_interfaces::reset_roiResponse> should match
// service_traits::DataType< ::zed_interfaces::reset_roi >
template<>
struct DataType< ::zed_interfaces::reset_roiResponse>
{
  static const char* value()
  {
    return DataType< ::zed_interfaces::reset_roi >::value();
  }
  static const char* value(const ::zed_interfaces::reset_roiResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ZED_INTERFACES_MESSAGE_RESET_ROI_H
