// Generated by gencpp from file zed_interfaces/set_roiRequest.msg
// DO NOT EDIT!


#ifndef ZED_INTERFACES_MESSAGE_SET_ROIREQUEST_H
#define ZED_INTERFACES_MESSAGE_SET_ROIREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace zed_interfaces
{
template <class ContainerAllocator>
struct set_roiRequest_
{
  typedef set_roiRequest_<ContainerAllocator> Type;

  set_roiRequest_()
    : roi()  {
    }
  set_roiRequest_(const ContainerAllocator& _alloc)
    : roi(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _roi_type;
  _roi_type roi;





  typedef boost::shared_ptr< ::zed_interfaces::set_roiRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::zed_interfaces::set_roiRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_roiRequest_

typedef ::zed_interfaces::set_roiRequest_<std::allocator<void> > set_roiRequest;

typedef boost::shared_ptr< ::zed_interfaces::set_roiRequest > set_roiRequestPtr;
typedef boost::shared_ptr< ::zed_interfaces::set_roiRequest const> set_roiRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::zed_interfaces::set_roiRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::zed_interfaces::set_roiRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::zed_interfaces::set_roiRequest_<ContainerAllocator1> & lhs, const ::zed_interfaces::set_roiRequest_<ContainerAllocator2> & rhs)
{
  return lhs.roi == rhs.roi;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::zed_interfaces::set_roiRequest_<ContainerAllocator1> & lhs, const ::zed_interfaces::set_roiRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace zed_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::zed_interfaces::set_roiRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zed_interfaces::set_roiRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zed_interfaces::set_roiRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zed_interfaces::set_roiRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zed_interfaces::set_roiRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zed_interfaces::set_roiRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::zed_interfaces::set_roiRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f8582525019d538cfd188d29f0c1b797";
  }

  static const char* value(const ::zed_interfaces::set_roiRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf8582525019d538cULL;
  static const uint64_t static_value2 = 0xfd188d29f0c1b797ULL;
};

template<class ContainerAllocator>
struct DataType< ::zed_interfaces::set_roiRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "zed_interfaces/set_roiRequest";
  }

  static const char* value(const ::zed_interfaces::set_roiRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::zed_interfaces::set_roiRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Set the Region of Interest for ZED SDK computing\n"
"\n"
"# Region of interest polygon as an array of normalized vertices. e.g. \"[[0.5,0.25],[0.75,0.5],[0.5,0.75],[0.25,0.5]]\"\n"
"# You can use\n"
"string roi\n"
;
  }

  static const char* value(const ::zed_interfaces::set_roiRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::zed_interfaces::set_roiRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_roiRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::zed_interfaces::set_roiRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::zed_interfaces::set_roiRequest_<ContainerAllocator>& v)
  {
    s << indent << "roi: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.roi);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ZED_INTERFACES_MESSAGE_SET_ROIREQUEST_H
