// Generated by gencpp from file zed_interfaces/set_roi.msg
// DO NOT EDIT!


#ifndef ZED_INTERFACES_MESSAGE_SET_ROI_H
#define ZED_INTERFACES_MESSAGE_SET_ROI_H

#include <ros/service_traits.h>


#include <zed_interfaces/set_roiRequest.h>
#include <zed_interfaces/set_roiResponse.h>


namespace zed_interfaces
{

struct set_roi
{

typedef set_roiRequest Request;
typedef set_roiResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_roi
} // namespace zed_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::zed_interfaces::set_roi > {
  static const char* value()
  {
    return "4d207dda349313cd8eabd3b09064e700";
  }

  static const char* value(const ::zed_interfaces::set_roi&) { return value(); }
};

template<>
struct DataType< ::zed_interfaces::set_roi > {
  static const char* value()
  {
    return "zed_interfaces/set_roi";
  }

  static const char* value(const ::zed_interfaces::set_roi&) { return value(); }
};


// service_traits::MD5Sum< ::zed_interfaces::set_roiRequest> should match
// service_traits::MD5Sum< ::zed_interfaces::set_roi >
template<>
struct MD5Sum< ::zed_interfaces::set_roiRequest>
{
  static const char* value()
  {
    return MD5Sum< ::zed_interfaces::set_roi >::value();
  }
  static const char* value(const ::zed_interfaces::set_roiRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::zed_interfaces::set_roiRequest> should match
// service_traits::DataType< ::zed_interfaces::set_roi >
template<>
struct DataType< ::zed_interfaces::set_roiRequest>
{
  static const char* value()
  {
    return DataType< ::zed_interfaces::set_roi >::value();
  }
  static const char* value(const ::zed_interfaces::set_roiRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::zed_interfaces::set_roiResponse> should match
// service_traits::MD5Sum< ::zed_interfaces::set_roi >
template<>
struct MD5Sum< ::zed_interfaces::set_roiResponse>
{
  static const char* value()
  {
    return MD5Sum< ::zed_interfaces::set_roi >::value();
  }
  static const char* value(const ::zed_interfaces::set_roiResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::zed_interfaces::set_roiResponse> should match
// service_traits::DataType< ::zed_interfaces::set_roi >
template<>
struct DataType< ::zed_interfaces::set_roiResponse>
{
  static const char* value()
  {
    return DataType< ::zed_interfaces::set_roi >::value();
  }
  static const char* value(const ::zed_interfaces::set_roiResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ZED_INTERFACES_MESSAGE_SET_ROI_H
