// Generated by gencpp from file darknet_ros_msgs/DetectionPose.msg
// DO NOT EDIT!


#ifndef DARKNET_ROS_MSGS_MESSAGE_DETECTIONPOSE_H
#define DARKNET_ROS_MSGS_MESSAGE_DETECTIONPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace darknet_ros_msgs
{
template <class ContainerAllocator>
struct DetectionPose_
{
  typedef DetectionPose_<ContainerAllocator> Type;

  DetectionPose_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , id(0)  {
    }
  DetectionPose_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , id(0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef int16_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::darknet_ros_msgs::DetectionPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::darknet_ros_msgs::DetectionPose_<ContainerAllocator> const> ConstPtr;

}; // struct DetectionPose_

typedef ::darknet_ros_msgs::DetectionPose_<std::allocator<void> > DetectionPose;

typedef boost::shared_ptr< ::darknet_ros_msgs::DetectionPose > DetectionPosePtr;
typedef boost::shared_ptr< ::darknet_ros_msgs::DetectionPose const> DetectionPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::darknet_ros_msgs::DetectionPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::darknet_ros_msgs::DetectionPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::darknet_ros_msgs::DetectionPose_<ContainerAllocator1> & lhs, const ::darknet_ros_msgs::DetectionPose_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::darknet_ros_msgs::DetectionPose_<ContainerAllocator1> & lhs, const ::darknet_ros_msgs::DetectionPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace darknet_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::darknet_ros_msgs::DetectionPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::darknet_ros_msgs::DetectionPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::darknet_ros_msgs::DetectionPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::darknet_ros_msgs::DetectionPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darknet_ros_msgs::DetectionPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darknet_ros_msgs::DetectionPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::darknet_ros_msgs::DetectionPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2e292010fca4af7fb1a5badef13ed2a5";
  }

  static const char* value(const ::darknet_ros_msgs::DetectionPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2e292010fca4af7fULL;
  static const uint64_t static_value2 = 0xb1a5badef13ed2a5ULL;
};

template<class ContainerAllocator>
struct DataType< ::darknet_ros_msgs::DetectionPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "darknet_ros_msgs/DetectionPose";
  }

  static const char* value(const ::darknet_ros_msgs::DetectionPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::darknet_ros_msgs::DetectionPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
"int16 id\n"
;
  }

  static const char* value(const ::darknet_ros_msgs::DetectionPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::darknet_ros_msgs::DetectionPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectionPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::darknet_ros_msgs::DetectionPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::darknet_ros_msgs::DetectionPose_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DARKNET_ROS_MSGS_MESSAGE_DETECTIONPOSE_H
