// Generated by gencpp from file darknet_ros_msgs/DetectionPoseList.msg
// DO NOT EDIT!


#ifndef DARKNET_ROS_MSGS_MESSAGE_DETECTIONPOSELIST_H
#define DARKNET_ROS_MSGS_MESSAGE_DETECTIONPOSELIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Header.h>
#include <darknet_ros_msgs/DetectionPose.h>

namespace darknet_ros_msgs
{
template <class ContainerAllocator>
struct DetectionPoseList_
{
  typedef DetectionPoseList_<ContainerAllocator> Type;

  DetectionPoseList_()
    : header()
    , image_header()
    , detectionposelist()  {
    }
  DetectionPoseList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , image_header(_alloc)
    , detectionposelist(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Header_<ContainerAllocator>  _image_header_type;
  _image_header_type image_header;

   typedef std::vector< ::darknet_ros_msgs::DetectionPose_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::darknet_ros_msgs::DetectionPose_<ContainerAllocator> >> _detectionposelist_type;
  _detectionposelist_type detectionposelist;





  typedef boost::shared_ptr< ::darknet_ros_msgs::DetectionPoseList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::darknet_ros_msgs::DetectionPoseList_<ContainerAllocator> const> ConstPtr;

}; // struct DetectionPoseList_

typedef ::darknet_ros_msgs::DetectionPoseList_<std::allocator<void> > DetectionPoseList;

typedef boost::shared_ptr< ::darknet_ros_msgs::DetectionPoseList > DetectionPoseListPtr;
typedef boost::shared_ptr< ::darknet_ros_msgs::DetectionPoseList const> DetectionPoseListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::darknet_ros_msgs::DetectionPoseList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::darknet_ros_msgs::DetectionPoseList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::darknet_ros_msgs::DetectionPoseList_<ContainerAllocator1> & lhs, const ::darknet_ros_msgs::DetectionPoseList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.image_header == rhs.image_header &&
    lhs.detectionposelist == rhs.detectionposelist;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::darknet_ros_msgs::DetectionPoseList_<ContainerAllocator1> & lhs, const ::darknet_ros_msgs::DetectionPoseList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace darknet_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::darknet_ros_msgs::DetectionPoseList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::darknet_ros_msgs::DetectionPoseList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::darknet_ros_msgs::DetectionPoseList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::darknet_ros_msgs::DetectionPoseList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darknet_ros_msgs::DetectionPoseList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darknet_ros_msgs::DetectionPoseList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::darknet_ros_msgs::DetectionPoseList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f6fc00ec917fb60a5053a8b4b47bca8";
  }

  static const char* value(const ::darknet_ros_msgs::DetectionPoseList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f6fc00ec917fb60ULL;
  static const uint64_t static_value2 = 0xa5053a8b4b47bca8ULL;
};

template<class ContainerAllocator>
struct DataType< ::darknet_ros_msgs::DetectionPoseList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "darknet_ros_msgs/DetectionPoseList";
  }

  static const char* value(const ::darknet_ros_msgs::DetectionPoseList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::darknet_ros_msgs::DetectionPoseList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"Header image_header\n"
"DetectionPose[] detectionposelist\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: darknet_ros_msgs/DetectionPose\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"int16 id\n"
;
  }

  static const char* value(const ::darknet_ros_msgs::DetectionPoseList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::darknet_ros_msgs::DetectionPoseList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.image_header);
      stream.next(m.detectionposelist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectionPoseList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::darknet_ros_msgs::DetectionPoseList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::darknet_ros_msgs::DetectionPoseList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "image_header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.image_header);
    s << indent << "detectionposelist[]" << std::endl;
    for (size_t i = 0; i < v.detectionposelist.size(); ++i)
    {
      s << indent << "  detectionposelist[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::darknet_ros_msgs::DetectionPose_<ContainerAllocator> >::stream(s, indent + "    ", v.detectionposelist[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DARKNET_ROS_MSGS_MESSAGE_DETECTIONPOSELIST_H
